### ISSUE TITLE
Problem with `ActiveRecord::Type::Value`

### ISSUE THREAD

**Issue by takahashim** [ruby/gem_rbs_collection#131]
There is a problem with current `gem_rbs_collection` when trying to use Steep in an application that uses `ActiveRecord::Type::Value`.

If I create a class that extends the class with `class Foo < ActiveRecord::Type::Value`, I get the following error.

```
[error] Cannot find type `ActiveRecord::Type::Value`
│ Diagnostic ID: RBS::UnknownTypeName
```

But when I try to add `ActiveRecord::Type::Value` to my rbs files, I get the following error.

```
[error] Declaration of `::ActiveRecord::Type::Value` is duplicated
│ Diagnostic ID: RBS::DuplicatedDeclaration
```

I guess this is because the current `ActiveRecord::Type::Value` is defined as an untyped constant.

https://github.com/ruby/gem_rbs_collection/blob/7726d637c93032cf8759dc6fd9196b5caaffc7df/gems/activerecord/6.0/activerecord-generated.rbs#L22012

https://github.com/rails/rails/blob/e75682b0f84c6ad607c62ea377b69876fd13f32d/activerecord/lib/active_record/type.rb#L67

I think we should not define as a constant and make it a class definition. What do you think?

**Comment by pocke** [comment]
Thanks for reporting this issue!


`AR::Type::Value` is an alias of `ActivceModel::Type::Value`, so this problem is caused.

https://github.com/rails/rails/blob/52f1f31c410f535032aa55401e0da583a9e768c0/activerecord/lib/active_record/type.rb#L59-L67

Currently RBS doesn't support class alias, so I do not have a simple solution.

We have the same problem on `AS::HashWithIndifferentAccess`.
In this case, I write `::HashWithIndifferentAccess` as a subsclass of `AS::HashWithIndifferentAccess`.
https://github.com/ruby/gem_rbs_collection/blob/a30c465651036a55ae3f1e0e0c4e2c23312b1e0a/gems/activesupport/6.0/activesupport-generated.rbs#L8082-L8085

This workaround works, but it introduces another issue. 
See https://github.com/ruby/rbs/issues/345


If your issue is high priority and the above workaround will work, we can apply the workaround to `AR::Type::Value` also.

I'll take this issue to the next RBS committer meeting. Please wait a moment to solve this issue completely 🙏

**Comment by takahashim** [comment]
Thank you for your answer. I understand.
`HashWithIndifferentAccess` is the same situation, so surely the same problem will happen with `ActiveRecord::Type::Value`.

I'm not

**Comment by fugakkbn** [comment]
I don't have any additional information, but I'm passing this along because I had the same problem.

Thanks for maintaining a great gem!
