### ISSUE TITLE
cannot install ActiveRecord 6.1 rbs on windows because of symlinks

### ISSUE THREAD

**Issue by sevenc-nanashi** [ruby/gem_rbs_collection#180]
`activerecord/6.1/activerecord-generated.rbs` and `activerecord/6.1/activerecord.rbs` are symlinks, so they're cannot be installed on windows.
On windows, symlinks aren't resolved, so the rbs are just file of `../6.0/activerecord-generated.rbs` (or `../6.0/activerecord.rbs`).

(Maybe I should post the issue to ruby/rbs?)

**Comment by pocke** [comment]
Thanks for reporting the issue. 

I do not have any plan to support Windows in the near future. Because the RBS maintainers don't use Windows (I guess mame-san uses WSL2 but it is a Linux technically), and I guess there are only a few RBS users on Windows.
The symlinks reduce maintenance costs actually, so I don't agree that we just replace them with copied files.


However, I do not against supporting Windows in another way. I think RBS should work on Windows, but I think maintenance cost is more important than Windows support because we only have a few maintainers.

If you have any idea to support Windows at a low cost, feel free to implement it 👍

Actually I do not know how many users use RBS on Windows. If there are many Windows users, I'll change the priority. So I recommend do +1 this issue for Windows users.


> (Maybe I should post the issue to ruby/rbs?)

You do not need it for now 🙌
If you have any solutions that need to change ruby/rbs, feel free to open an issue!

**Comment by sevenc-nanashi** [comment]
Hmm, so what about making `rbs collection` copy the file if the file is just a path?

**Comment by pocke** [comment]
> Hmm, so what about making rbs collection copy the file if the file is just a path?

It probably solves this problem but it looks ad-hoc approach. So I'd like to avoid it if I can.


By the way, apparently recent Windows support symlinks. How about enabling symlinks on your computer? ref: https://stackoverflow.com/a/59761201
It does not need to implement anything, so we can keep the code simple.

**Comment by sevenc-nanashi** [comment]
> By the way, apparently recent Windows support symlinks. How about enabling symlinks on your computer? ref: https://stackoverflow.com/a/59761201

It worked!

**Comment by pocke** [comment]
🎉 🎉 

I'll close this issue. Feel free to reopen/recreate issue if you still have any problem!

Thanks.
