### ISSUE TITLE
"Type `singleton(::Event)` does not have method `find_by`",

### ISSUE THREAD

**Issue by djpate** [ruby/gem_rbs_collection#35]
Hello,

Trying to set this up here on a project using ActiveRecord.

```ruby
class Event < ActiveRecord::Base
end
```
with the following type definition
```ruby
class Event < ActiveRecord::Base
  attr_accessor email: String
end
```

if I try to use
```ruby
Event.find_by(id: 1)
```
I get the following error message

```
Type `singleton(::Event)` does not have method `find_by`
```

My Steepfile is as follows

```
target :app do
  signature 'app/**/*.rbs'
  check 'main.rb'
  check 'app'

  repo_path 'vendor/rbs/gem_rbs_collection/gems'
  ignore "vendor/**/*.rb"

  library 'pathname'
  library 'logger'
  library 'mutex_m'
  library 'date'
  library 'monitor'
  library 'singleton'
  library 'tsort'

  library 'activesupport'
  library 'actionpack'
  library 'activejob'
  library 'activemodel'
  library 'actionview'
  library 'activerecord'
  library 'railties'
end
```

**Comment by pocke** [comment]
Thanks for reporting the issue!


You need to add an `extend` to the `Event` type definition in order to enable `find_by` singleton method.


```ruby
# event.rbs

class Event < ActiveRecord::Base
  # ↓ it is necessary
  extend _ActiveRecord_Relation_ClassMethods[Event, untyped, untyped]

  attr_accessor email: String
end
```

The `_ActiveRecord_Relation_ClassMethods` interface is defined here https://github.com/ruby/gem_rbs_collection/blob/551969504a000b3a2f82dc32e4cb3dbc40ea2285/gems/activerecord/6.0.3.2/activerecord.rbs#L102


BTW, the `extend` is automatically added by [RBS Rails](https://github.com/pocke/rbs_rails). I think the type definitions should work standalone, which means it should work without RBS Rails, but I have no plan to solve the problem in the near future.
