### ISSUE TITLE
aws-sdk signature issues

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/gem_rbs_collection#355]
I found the following inconsistencies in the aws SDK signatures, which are done via a generator:

## message/body/message_body parameters in S3/SQS clients are incorrectly typed to "only IO"

Those parameters can also be a string (it seems that `Aws::S3::Types::body` and the same variant in SQS should have been handling that instead, when defined as. `::IO | String`).

## SQS client "send_message" incorrectly typed as well

`send_message` receives two hashes as parameters, "params" and "options". The RBS signature uses kwargs and mixes parameters from each. Ideally it should be using RBS records for each (although it's probably not possible because of [this](https://github.com/ruby/rbs/issues/504)).

## Aws::SQS::Errors::InvalidParameterValue error is missing

Potentially more are?

**Comment by ksss** [comment]
@HoneyryderChuck Thank you for raising the issue.

> message/body/message_body parameters in S3/SQS clients are incorrectly typed to "only IO"

I fixed this issue. Could you confirm this?
https://github.com/ruby/gem_rbs_collection/pull/354

> SQS client "send_message" incorrectly typed as well

You are right.
`Aws::SQS::Client#send_message` and all client methods parameters has "params" and "options" argument.

https://github.com/aws/aws-sdk-ruby/blob/bbe581191d8d0dc9be0f63be5b3656d655c5b8e0/gems/aws-sdk-sqs/lib/aws-sdk-sqs/client.rb#L2233C3-L2233C3

The current implementation is intentionally conscious of being able to check required keyword arguments.
There is a possible way to set the Record type as you mentioned, but it has the disadvantage of not being able to check for required keywords.
I believe this is happening because aws-sdk-ruby implements such dynamic required keyword arguments.
I have not found the best solution to this problem. I am looking for ideas.

> Aws::SQS::Errors::InvalidParameterValue error is missing

`Aws::SQS::Errors::InvalidParameterValue` is a dynamically generated class. Probably the name is obtained by HTTP response and the class is generated under Errors.

https://github.com/aws/aws-sdk-ruby/blob/bbe581191d8d0dc9be0f63be5b3656d655c5b8e0/gems/aws-sdk-core/lib/aws-sdk-core/errors.rb#L393

I have not been able to find a list of names that could occur as this error class and have been unable to define it.
Ideally, the error class should be generated automatically from the list of error definitions maintained by Aws.
There is some documentation currently found, but we do not know if it is the best method.

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/CommonErrors.html
